apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cmpProperty.fullname" . }}
  labels:
    {{- include "cmpProperty.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "cmpProperty.selectorLabels" . | nindent 6 }}
  template:
    metadata:    
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "cmpProperty.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cmpProperty.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
           {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: {{ .Values.service.livePath }}
          #     port: {{ .Values.service.internalPort }}
          #   initialDelaySeconds: 60
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: {{ .Values.service.readyPath }}
          #     port: {{ .Values.service.internalPort }}
          #   initialDelaySeconds: 60
          #   periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      # nodeSelector:
      #   {{- toYaml . | nindent 8 }}
      # {{- end }}
      # {{- with .Values.affinity }}
      # affinity:
      #   {{- toYaml . | nindent 8 }}
      # {{- end }}
      # {{- with .Values.tolerations }}
      # tolerations:
      #   {{- toYaml . | nindent 8 }}
      # {{- end }}
