apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.dns_name }}
  labels:
    {{- include "cmpProperty.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
  selector:
    {{- include "cmpProperty.selectorLabels" . | nindent 4 }}
